---

emitter: enum('telegram', 'email')

logging:
  logfile: str()

email:
  from: str()
  to: str()
  host: str()

telegram:
  token: str()
  chatid: int()

opnsense:
  host: any(ip(), str())
  self_signed: bool()
  api_key: str()
  api_secret: str()
